### ISSUE TITLE
not sure what to do but its not working can someone help me fix this

### ISSUE THREAD

**Issue by VodzGaming** [Shawminator/DayZeEditor#3]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DayZeEditor.Project.getModList()
   at DayZeEditor.Economy_Manager.Economy_Manager_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Shawminator** [comment]
Having a look at the code and where the error is it seem sthat it has not initialized an empty mod list.
did you restart the editor after populating the folder when creating a new project?
